language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
install: # misc setup that I didn't want to put in script
  - if [ $TRAVIS_OS_NAME == osx ]; then LIBNAME=libasar.dylib; else LIBNAME=libasar.so; fi
  - mkdir build
  - cd build
script:
  - cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
  - make
  - ctest -C MinSizeRel --output-on-failure
