version: '{build}'
image: Visual Studio 2015
install:
- cmd: >-
    mkdir build tests_tmp_dll tests_tmp_app

    cd build

    cmake -G "%CMAKE_TARGET%" ..
environment:
  matrix:
    - CMAKE_TARGET: "Visual Studio 14 2015"
      PLATFORM: "Win32"
    - CMAKE_TARGET: "Visual Studio 14 2015 Win64"
      PLATFORM: "x64"
build:
  verbosity: minimal
artifacts:
- path: build\src\asar\MinSizeRel\asar-standalone.exe
- path: build\src\asar\MinSizeRel\asar.dll
configuration: MinSizeRel
test_script:
  # We need to pass the DLL path as an absolute path because it is used to calculate the std defines location, which will throw a warning when it's a relative path
  - cmd: >-
      ctest -C MinSizeRel --output-on-failure
